# WEBSCAPING Ikman.lk House

In [1]:
import requests
from bs4 import BeautifulSoup 
import pandas as pd
import re
import numpy as np

In [4]:
baseurl =  "https://ikman.lk"

In [3]:

headers= {
    'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36'
}

In [1]:

baseurl =  "https://ikman.lk"


headers= {
    'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36'
}
productlinks=[]
data=[]


for x in range (1,5):
    r = requests.get(f'https://ikman.lk/en/ads/sri-lanka/houses-for-sale?sort=date&order=desc&buy_now=0&urgent=0&page={x}')
    soup= BeautifulSoup(r.content,'lxml')
 
    
        
    
    
    productlist=soup.find_all("li",class_="normal--2QYVk gtm-normal-ad")
        

           
    for item in productlist:
        for link in item.find_all('a',href=True):
            productlinks.append(baseurl + link['href'])

#print(len(productlinks))
#print(productlinks)

for link in productlinks:
    
    r=requests.get(link,headers=headers)

    soup= BeautifulSoup(r.content,'lxml')
    
    
    try:

        Address=[]
        Area_of_Land=[]
        Property_size=[]

        Bedrooms= soup.findAll('div',class_='word-break--2nyVq value--1lKHt',id= False)[1].text
        
        Bathrooms= soup.findAll('div',class_='word-break--2nyVq value--1lKHt',id= False)[2].text
        
        Advertiser= soup.find('div',class_='ellipsis--3FPDI contact-name--m97Sb').text.strip()
        
        Price= soup.find('div',class_='amount--3NTpl').text.strip()
        
        
        for item in soup.findAll(text=re.compile('Address:')):
            Address.append(item.find_next('div').text) 

        for item in soup.findAll(text=re.compile('Land size:')):
            Area_of_Land.append(item.find_next('div').text)
            
            
        for item in soup.findAll(text=re.compile('House size:')):
            Property_size.append(item.find_next('div').text)
                    
    except:
        Address=''
        Area_of_Land=''
        Bedrooms=''
        Bathrooms=''
        Property_size=''
        Advertiser=''
        Price= ''    
             
    house={
        'Address':Address,
        'Area_of_Land':Area_of_Land,
        'Bedrooms':Bedrooms,
        'Bathrooms':Bathrooms,
        'Property_size':Property_size,
        'Advertiser':Advertiser,
        'Price':Price   
    }
    
    data.append(house)
        
df = pd.DataFrame(data)

df.insert(0, 'Property_type', 'House')

df['Address'] = df['Address'].str.get(0)
df['Area_of_Land'] = df['Area_of_Land'].str.get(0)
df['Property_size'] = df['Property_size'].str.get(0)



df = df.dropna(how='any')
df = df.reset_index(drop=True)
df

,Property_type,Address,Area_of_Land,Bedrooms,Bathrooms,Property_size,Advertiser,Price
0,House,කුඩිරිප්පුව ගල්මුරුව හෙලේනා වත්ත මාදම්පේ,15.0 perches,3,1,"1,000.0 sqft",Hashini Kaushala,"Rs 4,000,000"
1,House,Pannipityia Talawatugoda Road,10.0 perches,4,4,"4,000.0 sqft",DILRUWAN REAL ESTATE,"Rs 49,500,000"
2,House,Jothikarama Road Kalalgoda Talawatugoda,10.0 perches,4,4,"3,000.0 sqft",Asantha Real Estate,"Rs 49,500,000"
3,House,Chapel Road Nugegoda,22.0 perches,4,4,"4,000.0 sqft",Asantha Real Estate,"Rs 91,000,000"
4,House,Indigolla Gampaha,9.0 perches,4,2,"2,800.0 sqft",Universal Residencies,"Rs 27,000,000"
...,...,...,...,...,...,...,...,...
84,House,Kahanthota road Malabe,8.0 perches,5,4,"3,600.0 sqft",Charuni,"Rs 35,000,000"
85,House,kasbawa,11.5 perches,4,3,"2,066.0 sqft",Priyankara Kavirathna,"Rs 18,500,000"
86,House,"Depanama, Pannipitiya",10.0 perches,4,3,"2,852.0 sqft",Priyankara Kavirathna,"Rs 33,000,000"
87,House,300 Meters to Makola Main Road,16.0 perches,4,2,"2,000.0 sqft",Siyane Real Estate,"Rs 17,500,000"
88,House,NUGEGODA MIRIHANA,18.0 perches,5,5,"8,000.0 sqft",Dream Homes Real Estate,"Rs 165,000,000"

In [2]:
df.Address = df.Address.apply(lambda x: np.nan if 'All' in x else x)
df.Property_size = df.Property_size.apply(lambda x: np.nan if 'All' in x else x)
df.Area_of_Land = df.Area_of_Land.apply(lambda x: np.nan if 'All' in x else x)
df

,Property_type,Address,Area_of_Land,Bedrooms,Bathrooms,Property_size,Advertiser,Price
0,House,කුඩිරිප්පුව ගල්මුරුව හෙලේනා වත්ත මාදම්පේ,15.0 perches,3,1,"1,000.0 sqft",Hashini Kaushala,"Rs 4,000,000"
1,House,Pannipityia Talawatugoda Road,10.0 perches,4,4,"4,000.0 sqft",DILRUWAN REAL ESTATE,"Rs 49,500,000"
2,House,Jothikarama Road Kalalgoda Talawatugoda,10.0 perches,4,4,"3,000.0 sqft",Asantha Real Estate,"Rs 49,500,000"
3,House,Chapel Road Nugegoda,22.0 perches,4,4,"4,000.0 sqft",Asantha Real Estate,"Rs 91,000,000"
4,House,Indigolla Gampaha,9.0 perches,4,2,"2,800.0 sqft",Universal Residencies,"Rs 27,000,000"
...,...,...,...,...,...,...,...,...
84,House,Kahanthota road Malabe,8.0 perches,5,4,"3,600.0 sqft",Charuni,"Rs 35,000,000"
85,House,kasbawa,11.5 perches,4,3,"2,066.0 sqft",Priyankara Kavirathna,"Rs 18,500,000"
86,House,"Depanama, Pannipitiya",10.0 perches,4,3,"2,852.0 sqft",Priyankara Kavirathna,"Rs 33,000,000"
87,House,300 Meters to Makola Main Road,16.0 perches,4,2,"2,000.0 sqft",Siyane Real Estate,"Rs 17,500,000"
88,House,NUGEGODA MIRIHANA,18.0 perches,5,5,"8,000.0 sqft",Dream Homes Real Estate,"Rs 165,000,000"

In [3]:
#data = data.astype(str)
#df = df.astype(pd.StringDtype())
#df.dtypes

In [4]:
#df.Address = df.Address.apply(lambda x: np.nan if 'All' in x else x)
#df.Property_size = df.Property_size.apply(lambda x: np.nan if 'All' in x else x)
#df.Area_of_Land = df.Area_of_Land.apply(lambda x: np.nan if 'All' in x else x)

# WEBSCAPING Ikman.lk Apartments

In [8]:
import requests
from bs4 import BeautifulSoup 
import pandas as pd
import re
import numpy as np

baseurl =  "https://ikman.lk"


headers= {
    'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36'
}
productlinks=[]
data=[]


for x in range (1,5):
    r = requests.get(f'https://ikman.lk/en/ads/sri-lanka/apartments-for-sale?sort=date&order=desc&buy_now=0&urgent=0&page={x}')
    soup= BeautifulSoup(r.content,'lxml')
 
    
        
    
    
    productlist=soup.find_all("li",class_="normal--2QYVk gtm-normal-ad")
        

           
    for item in productlist:
        for link in item.find_all('a',href=True):
            productlinks.append(baseurl + link['href'])

print(len(productlinks))
#print(productlinks)

for link in productlinks:
    
    r=requests.get(link,headers=headers)

    soup= BeautifulSoup(r.content,'lxml')
    
    
    try:

        Address=[]
        Area_of_Land=[]
        Property_size=[]

        Bedrooms= soup.findAll('div',class_='word-break--2nyVq value--1lKHt',id= False)[1].text
        
        Bathrooms= soup.findAll('div',class_='word-break--2nyVq value--1lKHt',id= False)[2].text
        
        Advertiser= soup.find('div',class_='ellipsis--3FPDI contact-name--m97Sb').text.strip()
        
        Price= soup.find('div',class_='amount--3NTpl').text.strip()
        
        
        for item in soup.findAll(text=re.compile('Address:')):
            Address.append(item.find_next('div').text) 

        #for item in soup.findAll(text=re.compile('Land size:')):
            #Area_of_Land.append(item.find_next('div').text)
            
            
        for item in soup.findAll(text=re.compile('Size:')):
            Property_size.append(item.find_next('div').text)
                    
    except:
        Address=''
        Area_of_Land=''
        Bedrooms=''
        Bathrooms=''
        Property_size=''
        Advertiser=''
        Price= ''    
             
    house={
        'Address':Address,
        #'Area_of_Land':Area_of_Land,
        'Bedrooms':Bedrooms,
        'Bathrooms':Bathrooms,
        'Property_size':Property_size,
        'Advertiser':Advertiser,
        'Price':Price   
    }
    
    data.append(house)
        
df1 = pd.DataFrame(data)

df1.insert(0, 'Property_type', 'Apratments')

df1['Address'] = df1['Address'].str.get(0)
#df1['Area_of_Land'] = df1['Area_of_Land'].str.get(0)
df1['Property_size'] = df1['Property_size'].str.get(0)

df1 = df1.dropna(how='any')
df1 = df1.reset_index(drop=True)
df1

106

,Property_type,Address,Bedrooms,Bathrooms,Property_size,Advertiser,Price
0,Apratments,Hevlock City Colombo 05,2,2,"1,184 sqft",Zam Zam Properties,"Rs 50,000,000"
1,Apratments,Templers Road Mt Lavinia,3,3,"1,435 sqft",Serendib Real Estates,"Rs 26,000,000"
2,Apratments,Orchid 2 Apartment,3,2,"1,100 sqft",Sell Fast | Galle | DigiWorld Ad,"Rs 27,500,000"
3,Apratments,Barners place Colombo 7,3,4,"4,865 sqft",Zam Zam Properties,"Rs 325,000,000"
4,Apratments,Union Place Colombo,3,2,"1,200 sqft",Zam Zam Properties,"Rs 53,000,000"
...,...,...,...,...,...,...,...
65,Apratments,Dehiwala Nadimala Bellantara junction Somarath...,2,2,"1,100 sqft",Wasana Homes And Lands,"Rs 20,000,000"
66,Apratments,Harmers Avenue,3,3,"1,150 sqft",Zam Zam Properties,"Rs 27,500,000"
67,Apratments,Oval View Apartments,2,1,678 sqft,Dayan,"Rs 50,000,000"
68,Apratments,Wattala,2,2,950 sqft,Central 7,"Rs 16,500,000"
69,Apratments,Mtlavinia,10+,10+,"6,000 sqft",House Solution & Construction Rajkumar,"Rs 95,000,000"

In [5]:
## test link represent the house[0]
testlink="https://ikman.lk/en/ad/two-story-house-with-land-for-sale-in-horahena-road-kottawa-for-sale-colombo"
r = requests.get(testlink, headers=headers)
soup = BeautifulSoup(r.content, "lxml")

In [8]:
Advertiser= soup.find('div',class_='ellipsis--3FPDI contact-name--m97Sb').text.strip()
Advertiser

'Chandana Gunathilake'

In [18]:
contact_num=soup.find_all("div","phone-numbers--2COKR")
contact_num

[]